# 端口号
server:
  port: 6666
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzuli?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zzuli
    password: zzuli
  # 发送邮件配置
  mail:
    port: 465
    host: smtp.qq.com
    username: 1807366859@qq.com
    password: nlluhqsyjryobeig
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
        debug: true
# 查询时 java 驼峰命名自动转为_线形式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
# 日志配置文件的位置
logging:
  config: classpath:logback-spring.xml
pool:
  # thread 线程池配置
  corePoolSize: 8
  maximumPoolSize: 8
  keepAliveTime: 60
  capacity: 100




