spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzuli?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zzuli
    password: zzuli
  profiles:
    active: dev
  mail:
    port: 465
    host: smtp.qq.com
    username: 1807366859@qq.com
    password: nlluhqsyjryobeig
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
        debug: true
server:
  port: 6666
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭
logging:
  config: classpath:logback-spring.xml


